#Right motor must always be called rightMotor, left motor must always be leftMotor. Look through motorHelper to see what values are necessary,
#it varies by motor.
driveMotors:
  rightMotor:
    channel: 30
    type: "CANTalonFX"
    inverted: True
    pid:
      controlType: "Position"
      feedbackDevice: 0
      kPreScale: 4096
      kP: 0
      kI: 0
      kD: 0
      kF: 0
      sensorPhase: True

  rightFollower:
    channel: 31
    masterChannel: 1
    type: "CANTalonFXFollower"
    inverted: False

  leftMotor:
    channel: 40
    type: "CANTalonFX"
    inverted: True
    pid:
      controlType: "Velocity"
      feedbackDevice: 1
      kPreScale: 4096
      kP: .01
      kD: 0
      kI: .0000001
      kF: 0
      sensorPhase: True

  leftFollower:
    channel: 41
    masterChannel: 0
    type: "CANTalonFXFollower"
    inverted: False

  loaderMotor:
    channel: 11
    type: "SparkMax"
    inverted: True
    pid: Null
    motorType: "Brushed"

  intakeMotor:
    channel: 51
    type: "SparkMax"
    inverted: True
    pid: Null
    motorType: "Brushed"

  shooterMotor:
    channel: 52
    type: "CANTalonFX"
    inverted: True
    pid:
      controlType: "Velocity"
      feedbackDevice: 0
      kPreScale: 6
      kP: 0.0001
      kI: 0
      kD: 0
      kF: 0
      sensorPhase: True
    motorType: "Brushless"