#Right motor must always be called rightMotor, left motor must always be leftMotor. Look through motorHelper to see what values are necessary,
#it varies by motor.
motors:
  rightMotor:
    channel: 30
    type: "CANTalonFX"
    inverted: False
    pid: Null

  rightFollower:
    channel: 31
    masterChannel: 30
    type: "CANTalonFXFollower"
    inverted: False

  leftMotor:
    channel: 20
    type: "CANTalonFX"
    inverted: False
    pid: Null

  leftFollower:
    channel: 21
    masterChannel: 20
    type: "CANTalonFXFollower"
    inverted: False

  winchMotor:
    channel: 40
    type: "SparkMax"
    inverted: False
    motorType: "Brushless"
    pid:
      controlType: "Velocity"
      feedbackDevice: 2
      kPreScale: 6
      kP: .1
      kD: 0
      kI: .0000001
      kF: 0
      sensorPhase: True
  
  winchFollower:
    channel: 41
    masterChannel: 40
    type: "SparkMaxFollower"
    motorType: "Brushless"
    inverted: True

  intakeMotor:
    channel: 50
    type: "CANTalonSRX"
    inverted: False
    pid: Null

  loaderMotor:
    channel: 51
    type: "CANTalonSRX"
    inverted: False
    pid: Null

  shooterMotor:
    channel: 52
    type: "SparkMax"
    inverted: True
    motorType: "Brushless"
    pid: Null
