# for motors, use "rightMotorChannel" for right motor leader, "leftMotorChannel" for left motor leader
# "rightFollower(number of follower starting at 0)Channel" such as rightFollower0Channel and then rightFollower1Channel
# Same goes for left followers
# for ramp rate, "use ramprate" or "rotramprate" for rotation
driveMotors:
  rightMotor:
    channel: 1
    type: "CANTalonFX"
    inverted: True
    pid:
      controlType: "Position"
      feedbackDevice: 0
      kPreScale: 4096
      kP: 0
      kI: 0
      kD: 0
      kF: 0
      sensorPhase: True
  leftMotor:
    channel: 0
    type: "CANTalonFX"
    inverted: True
    pid:
      controlType: "Velocity"
      feedbackDevice: 1
      kPreScale: 4096
      kP: .01
      kD: 0
      kI: .0000001
      kF: 0
      sensorPhase: True
    